import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedArnoldLeonardoWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedSarahConnorWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedAfwanNoemarnovWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedPostingWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedArrow1Widget18.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedPostingWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedMyconnectionWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedCompanyWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedpostingwidget2/generated/GeneratedMenubarWidget9.dart';

/* Frame Posting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPostingWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 188.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedCompanyWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 289.0,
                child: GeneratedArnoldLeonardoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 289.0,
                child: GeneratedSarahConnorWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 289.0,
                child: GeneratedAfwanNoemarnovWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget9(),
              ),
              Positioned(
                left: 21.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedPostingWidget3(),
              ),
              Positioned(
                left: 194.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedPostingWidget5(),
              ),
              Positioned(
                left: 225.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 20.0,
                child: GeneratedMyconnectionWidget2(),
              ),
              Positioned(
                left: 48.2091064453125,
                top: 36.0,
                right: null,
                bottom: null,
                width: 18.209138870239258,
                height: 1.2246468525851679e-16,
                child: GeneratedArrow1Widget18(),
              )
            ]),
      ),
    ));
  }
}
