import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget12/generated/GeneratedRemoveWidget64.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget12/generated/GeneratedAddworkexperienceWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget12/generated/GeneratedUndoChangesWidget14.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget12/generated/GeneratedButtonremovesaveWidget18.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget12/generated/GeneratedPopupWidget14.dart';

/* Frame Undo Changes ?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUndoChangesWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget64(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 491.0,
                child: GeneratedAddworkexperienceWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedButtonremovesaveWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget14(),
              ),
              Positioned(
                left: 125.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedUndoChangesWidget14(),
              )
            ]),
      ),
    ));
  }
}
