import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedRectangle233Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/Generated668kWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/Generated445kWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedPartTimeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/Generated389kWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedRemoteJobWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedHeadhunting11Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedMenubarWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedFullTimeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedEllipse96Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedHelloOrlandoDiggsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedRectangle234Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedMaskgroupWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedRectangle232Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedMaskgroupWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedVectorWidget112.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedJobRecommendationWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedhomescreenwidget/generated/GeneratedFindYourJobWidget.dart';

/* Frame Home Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 186.0,
                child: GeneratedJobRecommendationWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 23.0,
                child: GeneratedFindYourJobWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse96Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.02586206896551724;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 21.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.136,
                        translateY: constraints.maxHeight * 0.7561576354679803,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget112())
                  ]);
                }),
              ),
              Positioned(
                left: 23.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 56.0,
                child: GeneratedHelloOrlandoDiggsWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 181.0,
                child: GeneratedMaskgroupWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 170.0,
                child: GeneratedRectangle232Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 75.0,
                child: GeneratedRectangle233Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 75.0,
                child: GeneratedRectangle234Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 20.0,
                child: GeneratedRemoteJobWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 26.0,
                child: Generated445kWidget(),
              ),
              Positioned(
                left: 244.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 26.0,
                child: Generated668kWidget(),
              ),
              Positioned(
                left: 244.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 26.0,
                child: Generated389kWidget(),
              ),
              Positioned(
                left: 236.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 20.0,
                child: GeneratedPartTimeWidget(),
              ),
              Positioned(
                left: 239.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 20.0,
                child: GeneratedFullTimeWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 88.0,
                child: GeneratedGroup65Widget(),
              ),
              Positioned(
                left: 309.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedMaskgroupWidget1(),
              ),
              Positioned(
                left: 81.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedHeadhunting11Widget(),
              )
            ]),
      ),
    ));
  }
}
