import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedinstitutionnamewidget6/generated/GeneratedBackWidget39.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedinstitutionnamewidget6/generated/GeneratedAddskillWidget3.dart';

/* Frame Institution name
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInstitutionnameWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget39(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 516.0,
                child: GeneratedAddskillWidget3(),
              )
            ]),
      ),
    ));
  }
}
