import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedRectangle238Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedSalaryWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedSeniordesignerWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedRectangle236Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedFilterWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedBackWidget15.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedSeniordesignerWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedUIUXDesignWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedMenubarWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedLastupdateWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedMinimumSalaryWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedFilterWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedCaliforniaWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedDesignWidget9.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedSeniordesignerWidget14.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedMinimumSalaryWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget1/generated/GeneratedRectangle237Widget.dart';

/* Frame Filter
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilterWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget15(),
              ),
              Positioned(
                left: 162.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: GeneratedFilterWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 334.9999694824219,
                height: 528.0,
                child: GeneratedLastupdateWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 78.0,
                child: GeneratedFilterWidget3(),
              ),
              Positioned(
                left: 65.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 50.0,
                child: GeneratedMenubarWidget6(),
              ),
              Positioned(
                left: 24.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 50.0,
                child: GeneratedRectangle236Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 50.0,
                child: GeneratedRectangle237Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 50.0,
                child: GeneratedRectangle238Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 21.0,
                child: GeneratedDesignWidget9(),
              ),
              Positioned(
                left: 57.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 18.0,
                child: GeneratedUIUXDesignWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 21.0,
                child: GeneratedCaliforniaWidget7(),
              ),
              Positioned(
                left: 24.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 20.0,
                child: GeneratedMinimumSalaryWidget(),
              ),
              Positioned(
                left: 251.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 20.0,
                child: GeneratedMinimumSalaryWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 28.0,
                child: GeneratedSeniordesignerWidget12(),
              ),
              Positioned(
                left: 140.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 28.0,
                child: GeneratedSeniordesignerWidget13(),
              ),
              Positioned(
                left: 256.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 28.0,
                child: GeneratedSeniordesignerWidget14(),
              ),
              Positioned(
                left: 22.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 123.0,
                child: GeneratedSalaryWidget1(),
              )
            ]),
      ),
    ));
  }
}
