import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedMenubarWidget14.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedWriteWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedIlkayGundoganWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedAndyRobertsonWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedAlexMorganWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedGiorgioChielliniWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedSearchWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedMessagesWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedAlessandroBastoniWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedOptionsWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedMeganRapinoeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmessagewidget/generated/GeneratedRemoveWidget8.dart';

/* Frame Message
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedAndyRobertsonWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 50.0,
                child: GeneratedGiorgioChielliniWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 50.0,
                child: GeneratedAlexMorganWidget(),
              ),
              Positioned(
                left: 312.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 72.0,
                child: GeneratedRemoveWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedMeganRapinoeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 50.0,
                child: GeneratedAlessandroBastoniWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 50.0,
                child: GeneratedIlkayGundoganWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedWriteWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedSearchWidget12(),
              ),
              Positioned(
                left: 331.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedOptionsWidget13(),
              ),
              Positioned(
                left: 140.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 31.0,
                child: GeneratedMessagesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget14(),
              )
            ]),
      ),
    ));
  }
}
