import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedYouhavenotreceivedtheemailResendWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedSaveWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedUndraw_message_sent_re_q2kl1Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedSignupwithGoogleWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedWehavesenttheresetpasswordtotheemailaddressbrandoneloui.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcheckyouremailwidget/generated/GeneratedCheckYourEmailWidget1.dart';

/* Frame Check Your Email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckYourEmailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedSaveWidget4(),
              ),
              Positioned(
                left: 28.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedSignupwithGoogleWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 40.0,
                child:
                    GeneratedWehavesenttheresetpasswordtotheemailaddressbrandoneloui(),
              ),
              Positioned(
                left: 73.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 21.0,
                child: GeneratedYouhavenotreceivedtheemailResendWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 41.0,
                child: GeneratedCheckYourEmailWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 109.0,
                child: GeneratedUndraw_message_sent_re_q2kl1Widget1(),
              )
            ]),
      ),
    ));
  }
}
