import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsearchwidget/generated/GeneratedBackWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsearchwidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsearchwidget/generated/GeneratedPopularjobsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsearchwidget/generated/GeneratedMenubarWidget5.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 280.0,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 659.0,
                child: GeneratedPopularjobsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget5(),
              )
            ]),
      ),
    ));
  }
}
