import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedInformationWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedAddyourCVResumetoapplyforajobWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedMenubarWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedBackWidget8.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedGroup48Widget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedUploadCVWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget/generated/GeneratedUploadCVResumeWidget.dart';

/* Frame Upload CV
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadCVWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget8(),
              ),
              Positioned(
                left: 29.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedMenubarWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 266.0,
                child: GeneratedInformationWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 75.0,
                child: GeneratedUploadCVResumeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 20.0,
                child: GeneratedUploadCVWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 18.0,
                child: GeneratedAddyourCVResumetoapplyforajobWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 215.0,
                child: GeneratedGroup48Widget2(),
              )
            ]),
      ),
    ));
  }
}
