import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedGoogleincWidget20.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedGoogleincWidget18.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedGoogleincWidget19.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedBackWidget28.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedGoogleincWidget22.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedGoogleincWidget21.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget/generated/GeneratedReadallWidget.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 121.0,
                child: GeneratedGoogleincWidget18(),
              ),
              Positioned(
                left: 20.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 121.0,
                child: GeneratedGoogleincWidget19(),
              ),
              Positioned(
                left: 20.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 121.0,
                child: GeneratedGoogleincWidget20(),
              ),
              Positioned(
                left: 20.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 121.0,
                child: GeneratedGoogleincWidget21(),
              ),
              Positioned(
                left: 20.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 121.0,
                child: GeneratedGoogleincWidget22(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget28(),
              ),
              Positioned(
                left: 125.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 31.0,
                child: GeneratedNotificationsWidget1(),
              ),
              Positioned(
                left: 310.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 18.0,
                child: GeneratedReadallWidget(),
              )
            ]),
      ),
    ));
  }
}
