import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednonotificationswidget/generated/GeneratedIllustrationWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednonotificationswidget/generated/GeneratedBackWidget33.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednonotificationswidget/generated/GeneratedNoSavingsWidget5.dart';

/* Frame No notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNonotificationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget33(),
              ),
              Positioned(
                left: 90.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 74.0,
                child: GeneratedNoSavingsWidget5(),
              ),
              Positioned(
                left: 97.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 219.9061279296875,
                height: 207.9895782470703,
                child: GeneratedIllustrationWidget3(),
              )
            ]),
      ),
    ));
  }
}
