import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget17/generated/GeneratedBackWidget26.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget17/generated/GeneratedCompanyWidget18.dart';

/* Frame Company
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCompanyWidget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget26(),
              ),
              Positioned(
                left: 19.49983024597168,
                top: 76.0,
                right: null,
                bottom: null,
                width: 335.50018310546875,
                height: 752.0,
                child: GeneratedCompanyWidget18(),
              )
            ]),
      ),
    ));
  }
}
