import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedUIUXDesignerWidget16.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedDeleteallWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedPopupWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedUXResearcherWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedSaveJobWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedLeadDesignerWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget16/generated/GeneratedMenubarWidget15.dart';

/* Frame Options
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOptionsWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedUIUXDesignerWidget16(),
              ),
              Positioned(
                left: 20.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedLeadDesignerWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedUXResearcherWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget15(),
              ),
              Positioned(
                left: 144.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 28.0,
                child: GeneratedSaveJobWidget(),
              ),
              Positioned(
                left: 302.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 18.0,
                child: GeneratedDeleteallWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedPopupWidget3(),
              ),
              Positioned(
                left: 1.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 299.0,
                child: GeneratedGroup62Widget(),
              )
            ]),
      ),
    ));
  }
}
