import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedMenubarWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedMaskgroupWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedHiOrlandoDiggsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedBackgroundWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedFilterWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedJobRecommendationWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedSpecializationWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedIconNotificationsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedMakeajobWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedPopupWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedSearchWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcreatjoborpostwidget/generated/GeneratedGroup60Widget.dart';

/* Frame Creat Job or Post
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCreatJoborPostWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 335.5970764160156,
                height: 283.8001403808594,
                child: GeneratedSpecializationWidget12(),
              ),
              Positioned(
                left: 20.0,
                top: 548.8001708984375,
                right: null,
                bottom: null,
                width: 335.0,
                height: 186.0,
                child: GeneratedJobRecommendationWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget(),
              ),
              Positioned(
                left: 375.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 220.0,
                child: GeneratedBackgroundWidget1(),
              ),
              Positioned(
                left: 315.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedFilterWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 110.0,
                child: GeneratedSearchWidget5(),
              ),
              Positioned(
                left: 288.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconNotificationsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 308.0,
                child: GeneratedGroup60Widget(),
              ),
              Positioned(
                left: 138.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 20.0,
                child: GeneratedMakeajobWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 30.0,
                child: GeneratedHiOrlandoDiggsWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedMaskgroupWidget2(),
              )
            ]),
      ),
    ));
  }
}
