import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedlanguagewidget5/generated/GeneratedSaveWidget69.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedlanguagewidget5/generated/GeneratedAddLanguageWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedlanguagewidget5/generated/GeneratedBackWidget45.dart';

/* Frame Language
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLanguageWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget45(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 321.0,
                child: GeneratedAddLanguageWidget2(),
              ),
              Positioned(
                left: 81.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget69(),
              )
            ]),
      ),
    ));
  }
}
