import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedLastupdateWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedPositionWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedSalaryWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedSpecializationWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedTypeofworkplaceWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedJobtypeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedCityWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedMenubarWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedFilterWidget8.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedBackWidget16.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedfilterwidget7/generated/GeneratedExperienceWidget2.dart';

/* Frame Filter
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilterWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1938.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1938.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 156.0,
                              child: GeneratedJobtypeWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 726.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 156.0,
                              child: GeneratedPositionWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 335.0004577636719,
                              height: 201.0,
                              child: GeneratedCityWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1123.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 123.0,
                              child: GeneratedSalaryWidget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1266.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 277.0,
                              child: GeneratedExperienceWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1563.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 277.0,
                              child: GeneratedSpecializationWidget6(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 201.0,
                              child: GeneratedLastupdateWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 163.0,
                              child: GeneratedTypeofworkplaceWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1860.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 78.0,
                              child: GeneratedMenubarWidget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget16(),
                            ),
                            Positioned(
                              left: 167.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 31.0,
                              child: GeneratedFilterWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
