import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedGroup48Widget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedGoogleincWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedGroup58Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedGroup59Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedTabmenuWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedGoogleincWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedjobswidget1/generated/GeneratedPopularjobsWidget1.dart';

/* Frame Jobs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJobsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedTabmenuWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedPopularjobsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedGoogleincWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 817.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 203.0,
                child: GeneratedGoogleincWidget12(),
              ),
              Positioned(
                left: 1.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 192.0,
                child: GeneratedGroup48Widget6(),
              ),
              Positioned(
                left: 197.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 40.0,
                child: GeneratedGroup58Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 40.0,
                child: GeneratedGroup59Widget1(),
              )
            ]),
      ),
    ));
  }
}
