import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedDribbbleincWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedFacebookincWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedAppleincWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedReadallWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedBackWidget29.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedGoogleincWidget23.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedTwitterincWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednotificationswidget2/generated/GeneratedNotificationsWidget3.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedGoogleincWidget23(),
              ),
              Positioned(
                left: 20.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedDribbbleincWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedTwitterincWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedFacebookincWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedAppleincWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget29(),
              ),
              Positioned(
                left: 310.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 18.0,
                child: GeneratedReadallWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 31.0,
                child: GeneratedNotificationsWidget3(),
              )
            ]),
      ),
    ));
  }
}
