import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedyourapplicationwidget/generated/GeneratedYourapplicationWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedyourapplicationwidget/generated/GeneratedJobdetileWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedyourapplicationwidget/generated/GeneratedBackWidget30.dart';

/* Frame Your application
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourapplicationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget30(),
              ),
              Positioned(
                left: 108.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedYourapplicationWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 596.0,
                child: GeneratedJobdetileWidget(),
              )
            ]),
      ),
    ));
  }
}
