import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedGroup58Widget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedCompanyGalleryWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedOptionsWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedGroup59Widget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedWebsiteWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/Generated5picturesWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedBackWidget20.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedSinceWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedGroup48Widget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedButtonApplynowWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedTypeWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedTabmenuWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedHeadofficeWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedSpecializationWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedEmployeesizeWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedUnsplashwD1LRb9OeEoWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedImage4Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedAboutCompanyWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaboutuswidget2/generated/GeneratedIndustryWidget4.dart';

/* Frame About us
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutusWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1244.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1244.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget20(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1166.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 78.0,
                              child: GeneratedButtonApplynowWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 309.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 50.0,
                              child: GeneratedTabmenuWidget3(),
                            ),
                            Positioned(
                              left: 331.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedOptionsWidget10(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 370.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 166.0,
                              child: GeneratedAboutCompanyWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 553.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 40.0,
                              child: GeneratedWebsiteWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 40.0,
                              child: GeneratedIndustryWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 40.0,
                              child: GeneratedEmployeesizeWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 231.0,
                              height: 40.0,
                              child: GeneratedHeadofficeWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 793.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 40.0,
                              child: GeneratedTypeWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 853.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 40.0,
                              child: GeneratedSinceWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 913.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 56.0,
                              child: GeneratedSpecializationWidget10(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 989.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 19.0,
                              child: GeneratedCompanyGalleryWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 192.0,
                              child: GeneratedGroup48Widget7(),
                            ),
                            Positioned(
                              left: 196.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 40.0,
                              child: GeneratedGroup58Widget2(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 40.0,
                              child: GeneratedGroup59Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1029.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedImage3Widget1(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 1029.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedImage4Widget1(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 1029.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedUnsplashwD1LRb9OeEoWidget3(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 1079.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 18.0,
                              child: Generated5picturesWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
