import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitappreciationwidget/generated/GeneratedButtonremovesaveWidget17.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitappreciationwidget/generated/GeneratedAddworkexperienceWidget9.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitappreciationwidget/generated/GeneratedRemoveWidget61.dart';

/* Frame Edit Appreciation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditAppreciationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget61(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 491.0,
                child: GeneratedAddworkexperienceWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedButtonremovesaveWidget17(),
              )
            ]),
      ),
    ));
  }
}
