import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedChat1Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedTodayWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedSendMassageWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedOptionsWidget15.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedChat2Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedBackWidget27.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedRectangle106Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedIconSearchWidget8.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedChat1Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedChat3Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedAndyRobertsonWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedIconCallWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedJametCVUIUXDesignerWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchatwidget7/generated/GeneratedMaskgroupWidget8.dart';

/* Frame Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 66.0,
                child: GeneratedChat2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 84.0,
                child: GeneratedChat3Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 66.0,
                child: GeneratedChat1Widget(),
              ),
              Positioned(
                left: 94.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 128.0,
                child: GeneratedChat1Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedSendMassageWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 215.99998474121094,
                height: 94.0,
                child: GeneratedJametCVUIUXDesignerWidget(),
              ),
              Positioned(
                left: 169.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 21.0,
                child: GeneratedTodayWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 156.0,
                child: GeneratedRectangle106Widget(),
              ),
              Positioned(
                left: 331.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedOptionsWidget15(),
              ),
              Positioned(
                left: 296.4296875,
                top: 100.0,
                right: null,
                bottom: null,
                width: 24.570068359375,
                height: 24.359458923339844,
                child: GeneratedIconCallWidget(),
              ),
              Positioned(
                left: 331.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconSearchWidget8(),
              ),
              Positioned(
                left: 87.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 40.0,
                child: GeneratedAndyRobertsonWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget27(),
              ),
              Positioned(
                left: 26.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedMaskgroupWidget8(),
              )
            ]),
      ),
    ));
  }
}
