import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedCompanyWidget15.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedAddajobWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedTypeofworkplaceWidget8.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedTypeofworkWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedPopupWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedJoblocationWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedDescriptionWidget18.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedRemoveWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchoosejobtypewidget/generated/GeneratedJobpositionWidget5.dart';

/* Frame Choose Job Type
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChooseJobTypeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedTypeofworkplaceWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 159.0,
                child: GeneratedDescriptionWidget18(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedJoblocationWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedJobpositionWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedCompanyWidget15(),
              ),
              Positioned(
                left: 20.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedTypeofworkWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 23.0,
                child: GeneratedAddajobWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 446.99981689453125,
                child: GeneratedPopupWidget2(),
              )
            ]),
      ),
    ));
  }
}
