import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumev2widget/generated/GeneratedSaveWidget100.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumev2widget/generated/GeneratedAddworkexperienceWidget15.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumev2widget/generated/GeneratedGroup63Widget3.dart';

/* Frame Add Resume V2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddResumeV2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 471.0,
                child: GeneratedAddworkexperienceWidget15(),
              ),
              Positioned(
                left: 81.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget100(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 220.0,
                child: GeneratedGroup63Widget3(),
              )
            ]),
      ),
    ));
  }
}
