import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedAddPostWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedAddworkexperienceWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedPostWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedMaskgroupWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedMenubarWidget11.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedBrandoneLouisWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddpostwidget/generated/GeneratedBackWidget22.dart';

/* Frame Add Post
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddPostWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget11(),
              ),
              Positioned(
                left: 85.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 39.0,
                child: GeneratedBrandoneLouisWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 272.0,
                child: GeneratedAddworkexperienceWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget22(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 23.0,
                child: GeneratedAddPostWidget1(),
              ),
              Positioned(
                left: 329.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedPostWidget5(),
              ),
              Positioned(
                left: 18.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 56.0,
                child: GeneratedMaskgroupWidget3(),
              )
            ]),
      ),
    ));
  }
}
