import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget3/generated/GeneratedAddworkexperienceWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget3/generated/GeneratedRemoveWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget3/generated/GeneratedButtonremovesaveWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget3/generated/GeneratedPopupWidget6.dart';

/* Frame Undo Changes ?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUndoChangesWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget13(),
              ),
              Positioned(
                left: 20.0000057220459,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 535.0,
                child: GeneratedAddworkexperienceWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedButtonremovesaveWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget6(),
              )
            ]),
      ),
    ));
  }
}
