import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfullywidget/generated/GeneratedSignupwithGoogleWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfullywidget/generated/GeneratedUndraw_message_sent_re_q2kl1Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfullywidget/generated/GeneratedYourpasswordhasbeenupdatedpleasechangeyourpasswordregul.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfullywidget/generated/GeneratedSuccessfullyWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfullywidget/generated/GeneratedSaveWidget3.dart';

/* Frame Successfully
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSuccessfullyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedSaveWidget3(),
              ),
              Positioned(
                left: 29.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedSignupwithGoogleWidget3(),
              ),
              Positioned(
                left: 53.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 40.0,
                child:
                    GeneratedYourpasswordhasbeenupdatedpleasechangeyourpasswordregul(),
              ),
              Positioned(
                left: 95.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 44.0,
                child: GeneratedSuccessfullyWidget1(),
              ),
              Positioned(
                left: 118.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 117.0,
                child: GeneratedUndraw_message_sent_re_q2kl1Widget(),
              )
            ]),
      ),
    ));
  }
}
