import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedExploreallthemostexcitingjobrolesbasedonyourinterestand.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedFindYourDreamJobHereWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedRectangle225Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsplashscreenwidget/generated/GeneratedGroup75Widget.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 271.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 23.0,
                child: GeneratedLogoWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: -36.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 849.0,
                child: GeneratedRectangle225Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 116.0,
                child: GeneratedFindYourDreamJobHereWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 166.99996948242188,
                right: null,
                bottom: null,
                width: 311.0,
                height: 301.0,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 289.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 675.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 38.0,
                child:
                    GeneratedExploreallthemostexcitingjobrolesbasedonyourinterestand(),
              )
            ]),
      ),
    ));
  }
}
