import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedFREEWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedGroup18305Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRealtiUIKitWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedFindthepropertyofWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRealtiUIKitWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle139Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedFindthepropertyofWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle141Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcoverwidget1/generated/GeneratedRectangle34Widget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1307.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1600.0,
                      height: 960.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -53.0,
                              right: null,
                              bottom: null,
                              width: 1800.0,
                              height: 1360.0,
                              child: GeneratedRectangle139Widget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 189.741455078125,
                              right: null,
                              bottom: null,
                              width: 136.6885986328125,
                              height: 139.5765838623047,
                              child: GeneratedGroup48Widget(),
                            ),
                            Positioned(
                              left: 78.4072265625,
                              top: 337.8609619140625,
                              right: null,
                              bottom: null,
                              width: 467.0,
                              height: 178.0,
                              child: GeneratedRealtiUIKitWidget(),
                            ),
                            Positioned(
                              left: 89.0859375,
                              top: 502.3145751953125,
                              right: null,
                              bottom: null,
                              width: 521.0,
                              height: 51.0,
                              child: GeneratedFindthepropertyofWidget(),
                            ),
                            Positioned(
                              left: 89.0859375,
                              top: 594.15234375,
                              right: null,
                              bottom: null,
                              width: 271.0623779296875,
                              height: 217.84768676757812,
                              child: GeneratedRectangle10Widget(),
                            ),
                            Positioned(
                              left: 110.443603515625,
                              top: 589.880859375,
                              right: null,
                              bottom: null,
                              width: 233.35519409179688,
                              height: 151.49200439453125,
                              child: GeneratedRealtiUIKitWidget1(),
                            ),
                            Positioned(
                              left: 384.888916015625,
                              top: 631.528076171875,
                              right: null,
                              bottom: null,
                              width: 505.6125793457031,
                              height: 146.16390991210938,
                              child: GeneratedFindthepropertyofWidget1(),
                            ),
                            Positioned(
                              left: 800.0,
                              top: 86.8460693359375,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle26Widget(),
                            ),
                            Positioned(
                              left: 1054.1953125,
                              top: 164.185302734375,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle28Widget(),
                            ),
                            Positioned(
                              left: 1308.3907470703125,
                              top: 24.3392333984375,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle32Widget(),
                            ),
                            Positioned(
                              left: 800.0,
                              top: 606.8262939453125,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle27Widget(),
                            ),
                            Positioned(
                              left: 1054.1953125,
                              top: 684.1656494140625,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle29Widget(),
                            ),
                            Positioned(
                              left: 1308.3907470703125,
                              top: 544.319580078125,
                              right: null,
                              bottom: null,
                              width: 219.42701721191406,
                              height: 410.2666931152344,
                              child: GeneratedRectangle33Widget(),
                            ),
                            Positioned(
                              left: 754.0,
                              top: -108.431640625,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 1040.978515625,
                              top: -21.1180419921875,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle30Widget(),
                            ),
                            Positioned(
                              left: 1327.9571533203125,
                              top: -179.0,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle34Widget(),
                            ),
                            Positioned(
                              left: 754.0,
                              top: 474.1019287109375,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle15Widget(),
                            ),
                            Positioned(
                              left: 1040.978515625,
                              top: 561.41552734375,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle31Widget(),
                            ),
                            Positioned(
                              left: 1327.9571533203125,
                              top: 403.5338134765625,
                              right: null,
                              bottom: null,
                              width: 248.68459033966064,
                              height: 535.1692552566528,
                              child: GeneratedRectangle35Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 97.44898223876953,
                              child: GeneratedRectangle141Widget(),
                            ),
                            Positioned(
                              left: 34.18365478515625,
                              top: 8.16326904296875,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 86.0,
                              child: GeneratedFREEWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.055;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        88.0;

                                double percentHeight = 0.09166666666666666;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        88.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX:
                                          constraints.maxWidth * 0.058125,
                                      translateY: constraints.maxHeight *
                                          0.21979166666666666,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.02979156494140625;

                                final double height = constraints.maxHeight *
                                    0.034374916553497316;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.070625,
                                      y: constraints.maxHeight *
                                          0.24895833333333334,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup18305Widget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
