import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedIndustryWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedDescriptionWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedWebsiteWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedBackWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedCompanyWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedHeadofficeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedTypeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedRectangle58Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/Generated5picturesWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedSinceWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedUnsplashwD1LRb9OeEoWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedDescriptionWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedSpecializationWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedMenubarWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedRectangle57Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedCompanyGalleryWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedEmployeesizeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedBackWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget3/generated/GeneratedAboutCompanyWidget2.dart';

/* Frame Company
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCompanyWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1234.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1234.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget6(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 251.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 40.0,
                              child: GeneratedRectangle57Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 251.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 40.0,
                              child: GeneratedRectangle58Widget1(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 40.0,
                              child: GeneratedDescriptionWidget3(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 261.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 23.0,
                              child: GeneratedCompanyWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 213.0,
                              child: GeneratedAboutCompanyWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 543.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 40.0,
                              child: GeneratedWebsiteWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 40.0,
                              child: GeneratedIndustryWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 663.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 40.0,
                              child: GeneratedEmployeesizeWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 723.0,
                              right: null,
                              bottom: null,
                              width: 231.0,
                              height: 40.0,
                              child: GeneratedHeadofficeWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 783.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 40.0,
                              child: GeneratedTypeWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 40.0,
                              child: GeneratedSinceWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 903.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 56.0,
                              child: GeneratedSpecializationWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 979.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 19.0,
                              child: GeneratedCompanyGalleryWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1156.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 78.0,
                              child: GeneratedMenubarWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 215.0,
                              child: GeneratedGroup48Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1021.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedImage3Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 1021.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedImage4Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 1021.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 115.0,
                              child: GeneratedUnsplashwD1LRb9OeEoWidget2(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 1071.0,
                              right: null,
                              bottom: null,
                              width: 66.0,
                              height: 18.0,
                              child: Generated5picturesWidget1(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 261.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 23.0,
                              child: GeneratedDescriptionWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
