import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedAddworkexperienceWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedPostWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedMenubarWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedMaskgroupWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedOrlandoDiggsWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedAppleincWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedBackWidget23.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedBrandoneLouisWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsharedajobwidget/generated/GeneratedSharedaJobWidget1.dart';

/* Frame Shared a Job
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSharedaJobWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenubarWidget12(),
              ),
              Positioned(
                left: 85.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 16.0,
                child: GeneratedBrandoneLouisWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 324.0,
                child: GeneratedAddworkexperienceWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 153.0,
                child: GeneratedAppleincWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget23(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 23.0,
                child: GeneratedSharedaJobWidget1(),
              ),
              Positioned(
                left: 329.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedPostWidget6(),
              ),
              Positioned(
                left: 87.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 20.0,
                child: GeneratedOrlandoDiggsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 56.0,
                child: GeneratedMaskgroupWidget4(),
              )
            ]),
      ),
    ));
  }
}
