import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedBackWidget54.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedOldPasswordWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedUpdatePasswordWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedNewPasswordWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedupdatepasswordwidget/generated/GeneratedSaveWidget99.dart';

/* Frame Update Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUpdatePasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 81.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget99(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget54(),
              ),
              Positioned(
                left: 20.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 66.0,
                child: GeneratedOldPasswordWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 66.0,
                child: GeneratedNewPasswordWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 66.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 23.0,
                child: GeneratedUpdatePasswordWidget1(),
              )
            ]),
      ),
    ));
  }
}
