import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremovelanguagewidget/generated/GeneratedSaveWidget71.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremovelanguagewidget/generated/GeneratedBackWidget46.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremovelanguagewidget/generated/GeneratedPopupWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremovelanguagewidget/generated/GeneratedAddLanguageWidget3.dart';

/* Frame Remove Language
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRemoveLanguageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget46(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 321.0,
                child: GeneratedAddLanguageWidget3(),
              ),
              Positioned(
                left: 81.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget71(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget12(),
              )
            ]),
      ),
    ));
  }
}
