import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmyprofilev1widget/generated/GeneratedSaveWidget92.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmyprofilev1widget/generated/GeneratedAddworkexperienceWidget14.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedmyprofilev1widget/generated/GeneratedGroup63Widget2.dart';

/* Frame My Profile V1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyProfileV1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 471.0,
                child: GeneratedAddworkexperienceWidget14(),
              ),
              Positioned(
                left: 81.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget92(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 220.0,
                child: GeneratedGroup63Widget2(),
              )
            ]),
      ),
    ));
  }
}
