import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchangeworkexperiencewidget/generated/GeneratedBackWidget36.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchangeworkexperiencewidget/generated/GeneratedAddworkexperienceWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedchangeworkexperiencewidget/generated/GeneratedButtonremovesaveWidget2.dart';

/* Frame Change work experience
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChangeworkexperienceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget36(),
              ),
              Positioned(
                left: 20.0000057220459,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0000305175781,
                height: 535.0,
                child: GeneratedAddworkexperienceWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedButtonremovesaveWidget2(),
              )
            ]),
      ),
    ));
  }
}
