import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedNotificationsWidget9.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedPasswordWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedDarkModeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedBackWidget52.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedSaveWidget94.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsettingswidget/generated/GeneratedLogoutWidget.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedNotificationsWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedDarkModeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedPasswordWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedLogoutWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget94(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget52(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 26.0,
                child: GeneratedSettingsWidget1(),
              )
            ]),
      ),
    ));
  }
}
