import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedGroup48Widget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedCongratulationsyourapplicationhasbeensentWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedIllustrationWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedFindasimilarjobWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedSuccessfulWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedBacktohomeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedsuccessfulwidget/generated/GeneratedJametkudasiCVUIUXDesignerWidget2.dart';

/* Frame Successful
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSuccessfulWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 58.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 50.0,
                child: GeneratedFindasimilarjobWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 50.0,
                child: GeneratedBacktohomeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 75.0,
                child: GeneratedJametkudasiCVUIUXDesignerWidget2(),
              ),
              Positioned(
                left: 110.0,
                top: 365.3566589355469,
                right: null,
                bottom: null,
                width: 152.15841674804688,
                height: 151.64334106445312,
                child: GeneratedIllustrationWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 26.0,
                child: GeneratedSuccessfulWidget1(),
              ),
              Positioned(
                left: 54.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 18.0,
                child:
                    GeneratedCongratulationsyourapplicationhasbeensentWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 215.0,
                child: GeneratedGroup48Widget4(),
              )
            ]),
      ),
    ));
  }
}
