import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedPopupWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedFacebookincWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedDribbbleincWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedBackWidget31.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedAppleincWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedNotificationsWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedReadallWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedTwitterincWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoptionswidget37/generated/GeneratedGoogleincWidget26.dart';

/* Frame Options
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOptionsWidget37 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedGoogleincWidget26(),
              ),
              Positioned(
                left: 20.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedDribbbleincWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedTwitterincWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedFacebookincWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 143.0,
                child: GeneratedAppleincWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget31(),
              ),
              Positioned(
                left: 125.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 31.0,
                child: GeneratedNotificationsWidget4(),
              ),
              Positioned(
                left: 310.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 18.0,
                child: GeneratedReadallWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget4(),
              )
            ]),
      ),
    ));
  }
}
