import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednoresultsfoundwidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednoresultsfoundwidget/generated/GeneratedIllustrasiWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednoresultsfoundwidget/generated/GeneratedNoSavingsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatednoresultsfoundwidget/generated/GeneratedBackWidget14.dart';

/* Frame No results found
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoresultsfoundWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 40.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget14(),
              ),
              Positioned(
                left: 62.0,
                top: 528.820068359375,
                right: null,
                bottom: null,
                width: 251.0,
                height: 74.0,
                child: GeneratedNoSavingsWidget(),
              ),
              Positioned(
                left: 110.58251953125,
                top: 292.0000305175781,
                right: null,
                bottom: null,
                width: 156.3196258544922,
                height: 176.8201141357422,
                child: GeneratedIllustrasiWidget(),
              )
            ]),
      ),
    ));
  }
}
