import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoralwidget2/generated/GeneratedPopupWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoralwidget2/generated/GeneratedSaveWidget76.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoralwidget2/generated/GeneratedAddLanguageWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedoralwidget2/generated/GeneratedBackWidget48.dart';

/* Frame Oral
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOralWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget48(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 424.0,
                child: GeneratedAddLanguageWidget7(),
              ),
              Positioned(
                left: 81.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget76(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget13(),
              )
            ]),
      ),
    ));
  }
}
