import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedSkillWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedWorkexperienceWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedMenubarWidget19.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedEducationWidget9.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedAppreciationWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedResumeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedLanguageWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitprofilewidget1/generated/GeneratedAboutmeWidget8.dart';

/* Frame Edit Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1681.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1681.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 173.0,
                              child: GeneratedWorkexperienceWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 164.0,
                              child: GeneratedAboutmeWidget8(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 608.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 173.0,
                              child: GeneratedEducationWidget9(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1250.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 173.0,
                              child: GeneratedAppreciationWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1438.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 151.0,
                              child: GeneratedResumeWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 235.00001525878906,
                              child: GeneratedSkillWidget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1046.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 189.0,
                              child: GeneratedLanguageWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1609.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 72.0,
                              child: GeneratedMenubarWidget19(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 220.0,
                              child: GeneratedGroup63Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
