import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedAboutCompanyWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedOptionsWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedDescriptionWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedEmployeesizeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedBackWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedCompanyGalleryWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedWebsiteWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedSpecializationWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedBackWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedGroup47Widget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedIndustryWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedMenubarWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedTypeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedSinceWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedHeadofficeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedcompanywidget/generated/GeneratedTabmenuWidget.dart';

/* Frame Company
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCompanyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget4(),
              ),
              Positioned(
                left: 195.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedTabmenuWidget(),
              ),
              Positioned(
                left: 331.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedOptionsWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 213.0,
                child: GeneratedAboutCompanyWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 40.0,
                child: GeneratedWebsiteWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 40.0,
                child: GeneratedIndustryWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 40.0,
                child: GeneratedEmployeesizeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 40.0,
                child: GeneratedHeadofficeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 40.0,
                child: GeneratedTypeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 40.0,
                child: GeneratedSinceWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 903.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 56.0,
                child: GeneratedSpecializationWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 979.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 157.0,
                child: GeneratedCompanyGalleryWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 78.0,
                child: GeneratedMenubarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 177.0,
                child: GeneratedGroup47Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 23.0,
                child: GeneratedDescriptionWidget2(),
              )
            ]),
      ),
    ));
  }
}
