import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedPostionWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedGroup47Widget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedApplynowWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedInformationsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedLocationWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedOptionsWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedRequirementsWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedJobTypeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedRequirementsWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedSalaryWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget1/generated/GeneratedJobDescriptionWidget2.dart';

/* Frame Description
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDescriptionWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1692.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1692.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 248, 248, 248),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 154.0,
                              child: GeneratedJobDescriptionWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 322.0,
                              height: 207.0,
                              child: GeneratedRequirementsWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 236.0,
                              child: GeneratedRequirementsWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 721.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 218.0,
                              child: GeneratedLocationWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 964.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 354.0,
                              child: GeneratedInformationsWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBackWidget2(),
                            ),
                            Positioned(
                              left: 331.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedOptionsWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 177.0,
                              child: GeneratedGroup47Widget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: GeneratedSalaryWidget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 20.0,
                              child: GeneratedJobTypeWidget2(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 23.0,
                              child: GeneratedPostionWidget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 1614.0,
                              right: null,
                              bottom: null,
                              width: 270.0,
                              height: 50.0,
                              child: GeneratedApplynowWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
