import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumewidget/generated/GeneratedUploadCVResumeWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumewidget/generated/GeneratedSaveWidget88.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumewidget/generated/GeneratedUploadfilesinPDFformatupto5MBJustuploaditonceandyoucanu.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumewidget/generated/GeneratedBackWidget50.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddresumewidget/generated/GeneratedAddworkexperienceWidget12.dart';

/* Frame Add Resume
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddResumeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget50(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedAddworkexperienceWidget12(),
              ),
              Positioned(
                left: 81.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget88(),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 75.0,
                child: GeneratedUploadCVResumeWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 30.0,
                child:
                    GeneratedUploadfilesinPDFformatupto5MBJustuploaditonceandyoucanu(),
              )
            ]),
      ),
    ));
  }
}
