import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget/generated/GeneratedPopupWidget5.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget/generated/GeneratedUndoChangesWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget/generated/GeneratedSaveWidget34.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget/generated/GeneratedRemoveWidget9.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedundochangeswidget/generated/GeneratedAboutmeWidget4.dart';

/* Frame Undo Changes ?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUndoChangesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 284.0,
                child: GeneratedAboutmeWidget4(),
              ),
              Positioned(
                left: 81.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget5(),
              ),
              Positioned(
                left: 122.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 20.0,
                child: GeneratedUndoChangesWidget2(),
              )
            ]),
      ),
    ));
  }
}
