import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedJobDescriptionWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedApplynowWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedOptionsWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generateddescriptionwidget/generated/GeneratedRequirementsWidget.dart';

/* Frame Description
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDescriptionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 154.0,
                child: GeneratedJobDescriptionWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 207.0,
                child: GeneratedRequirementsWidget(),
              ),
              Positioned(
                left: 331.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedOptionsWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 50.0,
                child: GeneratedApplynowWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 177.0,
                child: GeneratedGroup47Widget(),
              )
            ]),
      ),
    ));
  }
}
