import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedGroup48Widget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedMenubarWidget4.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedAddyourCVResumetoapplyforajobWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedInformationWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedUploadCVWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedBackWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadcvwidget2/generated/GeneratedJametkudasiCVUIUXDesignerWidget.dart';

/* Frame Upload CV
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadCVWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget10(),
              ),
              Positioned(
                left: 29.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 50.0,
                child: GeneratedMenubarWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 235.0,
                child: GeneratedInformationWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 118.0,
                child: GeneratedJametkudasiCVUIUXDesignerWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 20.0,
                child: GeneratedUploadCVWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 18.0,
                child: GeneratedAddyourCVResumetoapplyforajobWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 215.0,
                child: GeneratedGroup48Widget3(),
              )
            ]),
      ),
    ));
  }
}
