import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedDescriptionWidget14.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedTypeofworkWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedPostWidget8.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedJobpositionWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedJoblocationWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedRemoveWidget2.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedTypeofworkplaceWidget3.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedCompanyWidget11.dart';
import 'package:flutterapp/jobfinderuiappapp/generatededitaddajobwidget/generated/GeneratedAddajobWidget2.dart';

/* Frame Edit Add a job
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditAddajobWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedTypeofworkplaceWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 159.0,
                child: GeneratedDescriptionWidget14(),
              ),
              Positioned(
                left: 20.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedJoblocationWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedJobpositionWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedCompanyWidget11(),
              ),
              Positioned(
                left: 20.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 85.0,
                child: GeneratedTypeofworkWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 23.0,
                child: GeneratedAddajobWidget2(),
              ),
              Positioned(
                left: 329.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedPostWidget8(),
              )
            ]),
      ),
    ));
  }
}
