import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremoveworkexperiencewidget/generated/GeneratedRemoveWidget17.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremoveworkexperiencewidget/generated/GeneratedAddworkexperienceWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremoveworkexperiencewidget/generated/GeneratedPopupWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedremoveworkexperiencewidget/generated/GeneratedButtonremovesaveWidget5.dart';

/* Frame Remove Work Experience ?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRemoveWorkExperienceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget17(),
              ),
              Positioned(
                left: 20.0000057220459,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 535.0,
                child: GeneratedAddworkexperienceWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedButtonremovesaveWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPopupWidget7(),
              )
            ]),
      ),
    ));
  }
}
