import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadresumewidget/generated/GeneratedAddworkexperienceWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadresumewidget/generated/GeneratedSaveWidget90.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadresumewidget/generated/GeneratedUploadfilesinPDFformatupto5MBJustuploaditonceandyoucanu1.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadresumewidget/generated/GeneratedJametkudasiCVUIUXDesignerWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generateduploadresumewidget/generated/GeneratedBackWidget51.dart';

/* Frame Upload resume
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadresumeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget51(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedAddworkexperienceWidget13(),
              ),
              Positioned(
                left: 81.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget90(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 30.0,
                child:
                    GeneratedUploadfilesinPDFformatupto5MBJustuploaditonceandyoucanu1(),
              ),
              Positioned(
                left: 20.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 118.0,
                child: GeneratedJametkudasiCVUIUXDesignerWidget7(),
              )
            ]),
      ),
    ));
  }
}
