import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAddajobWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAddWidget10.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAddWidget11.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedRemoveWidget1.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedEducationWidget6.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedPostWidget7.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedSkillWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAddWidget12.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAboutmeWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedWorkExperienceWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedAddWidget13.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedLanguageWidget.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddajobwidget/generated/GeneratedDescriptionWidget12.dart';

/* Frame Add a job
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddajobWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 70.0,
                child: GeneratedWorkExperienceWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 130.0,
                child: GeneratedAboutmeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 70.0,
                child: GeneratedEducationWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 70.0,
                child: GeneratedSkillWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 70.0,
                child: GeneratedLanguageWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 70.0,
                child: GeneratedDescriptionWidget12(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 23.0,
                child: GeneratedAddajobWidget1(),
              ),
              Positioned(
                left: 329.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedPostWidget7(),
              ),
              Positioned(
                left: 311.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget10(),
              ),
              Positioned(
                left: 311.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget11(),
              ),
              Positioned(
                left: 311.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget12(),
              ),
              Positioned(
                left: 311.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget13(),
              )
            ]),
      ),
    ));
  }
}
