import 'package:flutter/material.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddlanguagewidget4/generated/GeneratedSaveWidget74.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddlanguagewidget4/generated/GeneratedBackWidget47.dart';
import 'package:flutterapp/jobfinderuiappapp/generatedaddlanguagewidget4/generated/GeneratedAddLanguageWidget5.dart';

/* Frame Add Language
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddLanguageWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackWidget47(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 424.0,
                child: GeneratedAddLanguageWidget5(),
              ),
              Positioned(
                left: 81.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedSaveWidget74(),
              )
            ]),
      ),
    ));
  }
}
